### ISSUE TITLE
not loading in Max on OS X

### ISSUE THREAD

**Issue by pukunui** [impsnldavid/imp.push#3]
Hey David,

This isn't loading for me in Max - I get

imp.push: unable to load object bundle executable
 2016-05-25 08:48:00.529 Max[1228:89456] Cannot find executable for CFBundle 0x7fbc4d350290 </Users/a/Documents/Max 7/Packages/imp.push/externals/imp.push.mxo> (not loaded)

It's not building either.

Sorry that's as far as I have gotten - XCode 7.3.1 on 10.11.5, about 42 errors

**Comment by impsnldavid** [comment]
OK, XCode was annoyingly linking to the MacPorts version of libusb rather than the private build in the reposity (evidenced when I removed my MacPorts directory from the library search paths). Will fix shortly.

**Comment by pixsperdavid** [comment]
Should now be fixed

https://github.com/impsnldavid/imp.push/releases/tag/v0.1.1

**Comment by BjornVayner** [comment]
Small thing in regards to the update, the included help file still refers to 0.1.0.

Is there a way to disconnect and reconnect the display while its used in MFL? You can disconnect the whole Push from Live and then access the screen, but it needs a reboot to regain its functionality in Live. If I try it it now, I get the "device already in use -3 libusb" error in the Max window.

**Comment by mariohamann** [comment]
@impsnldavid Do you see any possibility to make imp.push usable in M4L? I would love to contribute, extend the README and add some working examples e. g. for movies, but this option would be a must-have. :)

P2D has nice docs with some examples – but it's crashing a lot in my tests and imp.push feels much more robust.
But the docs are of P2D are really fine, and it's possible to use it in M4L: https://sigabort.co/Assets/doc/P2D%20User%20Guide.pdf

> To use P2D inside Max for Live, create the `lmh_p2d` object with the `@m4l 1` attribute.

**Comment by pixsperdavid** [comment]
@mariohamann It's not something I'm particularly interested in looking into at the moment. To be truly useful in Live I think you need to be able to switch between an imp.push view and the native device view, and developing something like that is a much larger task than the entire current imp.push code! Plus I'm not convinced there's a non-hacky way to do it...

**Comment by mariohamann** [comment]
Thank you very much for your fast answer! Hm. Isn't just the main problem, that imp.push doesn't recognize when it is called from Ableton? I have the feeling that it's more a problem of the right environment check over here: https://github.com/impsnldavid/imp.push/blob/4cbed734bef102870fa26b80f548d42c73f4758f/src/imp.push.c#L347 – but I'm not very into it... interesting enough: In [this article](https://sonicbloom.net/de/kostenloser-max-hack-ermoeglicht-das-streaming-des-computerbildschirms-auf-das-display-von-push-2/) it seems that @DJUnit27 could get it working in M4L:

> Screen To Push 2 Display is a Max patch that requires the standalone version of Cycling '74's Max. However, Max patches can now be easily converted to Max for Live devices. All you have to do is create a new Max for Live device, copy the text from the Max patch and paste it into the patch window. Ricardo Balderas also said that he is considering creating a Max for Live version to make it even easier for those who want to use the hack.

Maybe he can help out?

**Comment by pixsperdavid** [comment]
Detecting whether you're running in the Live environment is trivial. The issue is that only one application can access a USB device at once. To get around this (and this is how I think P2D has implemented it) you would need to implement an intermediary which intercepts the connection from Live and allows you to combine it with data from imp.push. The task of creating this considerably dwarfs the roughly 8 hours I spent creating the object in the first place!
